### ISSUE TITLE
support predicates

### ISSUE THREAD

**Issue by WebFreak001** [ZILtoid1991/collections-d#1]
Most often you don't want to sort on data directly, but rather on specific keys of a struct for example or perform modifications before.

In the phobos sort function for example you can pass a less-than function that is `"a<b"` by default, this library should probably do something similar (while API breakage is still not a major concern)

You can use `std.functional` : [binaryFun](https://dlang.org/phobos/std_functional.html#binaryFun) to do this easily.

**Comment by ZILtoid1991** [comment]
I'll see what can I do after I do some refactoring work.

I've seen many standard library stuff using `alias less="a<b"`, and originally I've intended to use that if there wasn't for a bug that needed me to rewrite stuff.

**Comment by WebFreak001** [comment]
you would pretty much just need to change compare operations to first check for equality, then do the binaryFun!less(a, b) and then an else part for greater than.

If you have stuff with just one branch < and the other as else, you can just replace your `if (lhs < rhs)` with `if (binaryFun!less(lhs, rhs))` and it should be pretty easy to do.

**Comment by ZILtoid1991** [comment]
Come to my mind, shouldn't there be an `alias equal="a==b"` where it's applicable?

**Comment by ZILtoid1991** [comment]
Done for the SortedList so far, might do some refinement on the whole thing (I don't use `equal` outside of disallowing duplicates). Tomorrow I'll revise TreeMap too in a similar way.

**Comment by WebFreak001** [comment]
ah actually the std functions call the less than function twice:
```d
if (lessFun(a, b)) // less than
else if (lessFun(b, a)) // greater than
else // equal
```
