### ISSUE TITLE
Feature Request: Set

### ISSUE THREAD

**Issue by m3m0ry** [ZILtoid1991/collections-d#2]
Currently in the stdlib, there is no simple `set` to use.
This would be a great addition to this package.

**Comment by ZILtoid1991** [comment]
I'll see what I can do.

**Comment by ZILtoid1991** [comment]
I'm currently writing some.

Is it okay, if sets can be made from other collections by setting the template parameter `allowDuplicates` false?

**Comment by m3m0ry** [comment]
I have asked previously in the dlang forum. I have three different solutions in my head.
First is a sorted array (or list), without duplicates. A better one would be an RB-tree (with no duplicates). I usually just make an boolean AA. Which is fast, but little cumbersome to use.

**Comment by ZILtoid1991** [comment]
I have added some more features. I hope my solution for sets and set operators is good.

**Comment by m3m0ry** [comment]
This is awesome!
Thank you!
