### ISSUE TITLE
Ordered map

### ISSUE THREAD

**Issue by 89z** [ZILtoid1991/collections-d#3]
Does this project offer ordered maps?

- <https://wikipedia.org/wiki/Associative_array#Ordered_dictionary>
- <https://yaml.org/type/omap.html>

**Comment by ZILtoid1991** [comment]
To a lesser degree, `TreeMap` is like that by design. `opApply` does a left-to-right tree traversal, while `opApplyReverse` does the opposite. At one point I wanted to add a function that would've returned the n-th element of the Map, but I had better thing to do instead. Feel free to implement it if you need it!

I've designed `TreeMap` with integer values in mind, but probably can work with strings too if you write your own comparison function, as most string compare function only check for equality.

**Comment by 89z** [comment]
Sorry when I say order, I mean insertion order

**Comment by ZILtoid1991** [comment]
Then your closest bet would be `LinkedMap`, with elements inserted first being in the front as long as there's no key matches. However, as of now there's no `opApplyReverse` override in it, which I probably could add easily (it requires some metaprogramming trickery to get through D's attribute hell), alongside with a template modifier to put elements in the back even if there's a key match.

**Comment by 89z** [comment]
ah, I see it now, thanks. The descriptions in the Readme are pretty bare, so I missed it.

Would that be better than LinkedHashMap? I cant tell the difference

**Comment by ZILtoid1991** [comment]
I'll update the Readme to better reflect on things, especially as some of the code seems to be poorly formatted. This is not really an intended feature of `LinkedMap`, it's more of a byproduct of it's simplistic operation.

`LinkedHashMap` uses `LinkedMap` as it's backend. It's intended to be used as a lookup table more than anything else, so it only stores hashes of the keys, which could be important in certain circumstances, however it can be faster to compare e.g. fix 16 byte values than strings of varying sizes, and you can access any of the hashmaps with the hashes themselves. What you want to use will depend on your application, and what is more important for you. There's even the `HashMap` that uses `TreeMap` instead that has more optimized access complexity as long as you either happy with shorter hash values, or implement some function to order the longer ones.

**Comment by 89z** [comment]
I just want a simple ordered map, similar to PHP array:

https://php.net/language.types.array

my only requirement is that I can iterate the elements in insertion order. Also this is confusing:

> it only stores hashes of the keys

does that mean I wouldnt have access to the original keys? Cause I need that too.

**Comment by ZILtoid1991** [comment]
> does that mean I wouldnt have access to the original keys? Cause I need that too.

Currently the original keys are not stored. I'll add an option to preserve them as well as an option to modify the behavior of the order preservation and more foreach overrides, most likely tomorrow. I've looked up, and sometimes the keys need to be preserved.

**Comment by ZILtoid1991** [comment]
In the master branch, I've done some commit, including option to modify the behavior of overwriting preexisting keys. Due to I having to live a life and I got some paid job, I couldn't yet update the readme and the unit tests, but all current tests pass on DMD x64. Also no `foreach_reverse` as of now.

Let me know if you need some other functionality.

**Comment by 89z** [comment]
thank you very much! I think all is good - I think the readme should be updated, but no rush. However long it takes is fine

**Comment by ZILtoid1991** [comment]
Due to RSI I've got from some physical job, I'll be working much slower. Half of my hand is numb, it hurts to hold it in certain ways, and the non-emergency healthcare system is currently defunct in my country (not that it worked well before the pandemic).

**Comment by 89z** [comment]
Sorry to hear that. I got fired last month from my job of 5 years.

**Comment by ZILtoid1991** [comment]
Just made some big refactoring (made the maps two-way linked, fixed things I forgot previously), tomorrow I'll write some more unit tests and fix stuff if needed.

Also I would like some input on the new readme.md, I might do some future documentation too.

**Comment by 89z** [comment]
Whoa that new readme looks great!

I would suggest breaking the table into 2 tables if possible, one with the basic information, and another with more detailed information. You could put the 2nd table further down the page, or even on another page linked from the main readme. As it is now its too wide even with screen fully maximized.
Another option would be to use GitHub pages, then you could probably keep it as a single table. GitHub.com enforces maximum width, GitHub.io does not.

**Comment by ZILtoid1991** [comment]
I've just published a new alpha version containing enhancements I thought you would need.

I need to work on my other projects too. Until then, use the library as you wish, and please either report any reproducible bug or fix them yourself via a commit!

**Comment by ZILtoid1991** [comment]
Added some more unit tests, now I'm going to publish the final version.

Let me know if you encountered any bugs!

**Comment by 89z** [comment]
I have to be honest, when I posted this, I was trying to solve a problem. Since then, I decided that Ordered map wasnt the right solution to my problem. However I think its still and important structure to have available. Thank you
